### ISSUE TITLE
Nothing happens when I run a command in Rhino

### ISSUE THREAD

**Issue by tkhashi** [shuya-tamaru/GltfAttributesUserTextExporter#1]
I downloaded the released package (v1.0.0) and ran the command from Rhino, but nothing happened.

Are there any other steps I need to take?

## Reproduction steps
1. Install the plugin by following the "Installation" in the link
2. Run the command

## Environment
OS: Windows 11 Home x86_64
Rhinoceros: Version 8 SR9 (8.9.24194.18121, 2024-07-12)

## Notes
* Execution results.
![2024-07-18_20h14_36](https://github.com/user-attachments/assets/f1fb150a-dc7b-4854-8dfa-4411fae931c3)

* If you try cloning the source code and running debug from Visual Studio 2022, the following error will appear. 
![2024-07-18_20h20_29](https://github.com/user-attachments/assets/2c5040bd-7861-4b92-95b7-c5c0ebf9f465)

**Comment by shuya-tamaru** [comment]
Sorry, my explanation was completely insufficient. Rhino 7 is based on .NET Framework, while Rhino 8 is based on .NET Core. Since this plugin is created with .NET Framework, you need to switch the runtime to .NET Framework in Rhino 8 by running the 'SetDotNetRuntime' command in Rhino.

<img width="365" alt="スクリーンショット 2024-07-19 163908" src="https://github.com/user-attachments/assets/64060e5c-8a34-447c-aa28-cd480a2227ff">

**Comment by shuya-tamaru** [comment]
Sorry, my explanation was completely insufficient. Rhino 7 is based on .NET Framework, while Rhino 8 is based on .NET Core. Since this plugin is created with .NET Framework, you need to switch the runtime to .NET Framework in Rhino 8 by running the 'SetDotNetRuntime' command in Rhino.

<img width="365" alt="スクリーンショット 2024-07-19 163908" src="https://github.com/user-attachments/assets/7f15cb60-2ae9-4cee-aa1a-41f85be83826">

**Comment by tkhashi** [comment]
Thanks! It work!
